### ISSUE TITLE
Question: how does this compare to benchmark.js?

### ISSUE THREAD

**Issue by psirenny** [JoshuaWise/nodemark#1]
Am I correct in assuming that the library attempts to deal with noise and the garbage collector in a better way? Also, how accurate would the library be when browserified?

**Comment by JoshuaWise** [comment]
There is no clear-cut "winner", each has its advantages and disadvantages. Let me explain.

If you're testing something that takes longer than (approximately) 30 nanoseconds to execute (33 million ops/sec), both libraries will have practically equal precision. For operations faster than 30 nanoseconds, `benchmark.js` has better precision. But there is a **big** caveat.

The problem with `benchmark.js` is that it performs a single "setup" before running your test in a loop. It does not run the setup *during* the loop. Let's look at the following example:

```js
let obj;
function setup() {
  obj = {};
}
function test() {
  obj.foo = 'bar';
}
```

In this example, you're obviously trying to test the time it takes to assign a *new property* to an object. Unfortunately, after the first test execution, the same object will be used again and again, so really, you'll be measuring the time it takes to assign an *already-existing* property on an object.

This problem is practically (maybe even theoretically) impossible to avoid. For example, even if you generate a different key every time, there are two new problems introduced. For one, the object will grow and grow and grow, which will have drastic effects on performance that are not really applicable to the real world (objects with millions of properties will be very slow, and don't occur in real programs). To prevent the object from growing, you could try to delete the property in the `test` function, but then you're measuring that too, which prevents you from precisely measuring the thing you actually care about (assigning a new property).

You can see where this is going. This problem occurs in objects, arrays, etc. But it's worse than you think. In v8 (the JavaScript engine used by Node.js), whenever the contents of a string is read (such as invoking a regular expression, or using the string as an object key), it becomes "cached" and "optimized" in a way. You'll notice that the performance of reading a dynamically generated string is faster after the first few times. However, in the real world, most strings are only read once (such as user input, or an HTTP request to a web server). In those cases, you only care about the "unoptimized" performance. In `benchmark.js`, since you're using the same string every time, you cannot actually measure the value you care about.

It's very easy to write bad benchmarks with `benchmark.js`, and it's very hard to write good ones. `nodemark` solves this problem by executing the "setup" function before *every* test execution. This results is a slight loss of precision (it introduces some unavoidable noise in the order of nanoseconds), but allows you to actually measure the thing you're trying to measure.

I hope this explanation helps to understand the difference between the two libraries.

**Comment by JoshuaWise** [comment]
Oh, I should also mention that `nodemark` handles asynchronous benchmarks in a more accurate way.

**Comment by JoshuaWise** [comment]
I have not tested or examined using `nodemark` in the browser. I believe `benchmark.js` does some things to compensate for the precision of different timers that various browsers implement. In Node.js, this is not an issue because there's only a single runtime.

**Comment by psirenny** [comment]
> I hope this explanation helps to understand the difference between the two libraries.

Wow, yes! That was an incredibly helpful explanation. Thank you 😄
